vd/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from dictapp.views.pages import index, about, help
from dictapp.views.profile import profile, register_user, model_form_upload, handle_uploads

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^about/$', about, name='about'),
    url(r'^help/', help, name='help'),

    url(r'^accounts/register/$', register_user, name='register'),
    url(r'^accounts/login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': settings.LOGIN_REDIRECT_URL}, name='logout'),
    url(r'^accounts/', include('password_reset.urls')),

    url(r'^profile/([^/]+)/$', profile, name="profile"),
    url(r'^profile/([^/]+)/upload$', model_form_upload, name="upload"),
    url(r'^profile/([^/]+)/files$', handle_uploads, name="handle_uploads"),
    ]


if settings.DEBUG:
    urlpatterns += static(r'media/', document_root=settings.MEDIA_ROOT)

dictapp/models.py
#  -- coding: utf8 --
import os

from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from dictapp.es.utils import add_to_index


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class DictFile(models.Model):
    user = models.ForeignKey(User, auto_created=True)
    file = models.FileField(upload_to=user_directory_path)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    name = models.TextField(blank=True, null=True, max_length=600)

    def add_es(self):
        add_to_index(os.path.join(settings.MEDIA_ROOT, self.file.path))


class UserProfile(models.Model):
    user = models.OneToOneField(User)

    def __str__(self):
        return '{0} {1} ({2})'.format(self.user.first_name, self.user.last_name, self.user.username)

dictapp/views/profile.py
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import redirect, render, HttpResponse
from dictapp.forms import DictFileForm

from dictapp.forms import UserCreationForm
from dictapp.models import UserProfile, DictFile
from dictapp.views.validate import validate_it

import os

def register_callback(user):
    user_profile = UserProfile(user=user)
    user_profile.save()


def profile(request, username):
    user = User.objects.get(username=username)
    return render(request, 'profile.html', locals())


def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            if User.objects.filter(username=username):
                error = 'Пользователь с таким логином уже существует'
                return render(request, 'register.html', locals())

            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']

            user = User.objects.create_user(username, email, password=password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()

            user_profile = UserProfile(user=user)
            user_profile.save()

            user = authenticate(username=username, password=password)
            login(request, user)

            return redirect(request.GET.get('next', '/') or '/')

    form = UserCreationForm()
    next_page = request.GET.get('next', '/')
    return render(request, 'register.html', locals())


def model_form_upload(request, user):
    if request.method == 'POST':
        form = DictFileForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = DictFile(file=request.FILES['file'], user=request.user)
            newdoc.save()
            valid, error, name = validate_it(os.path.join(settings.MEDIA_ROOT, newdoc.file.path))
            if not valid:
                newdoc.delete()
            else:
                newdoc.name = name
                newdoc.save()
            show_form = True if not valid else False
            return render(request, 'dict_upload.html', {'form': form, 'show_form':show_form, 'valid':valid, 'error': error})
        else:
            render(request, 'dict_upload.html', {'form': form, 'show_form':True, 'valid':True})
    else:
        form = DictFileForm()
    return render(request, 'dict_upload.html', {'form': form, 'show_form':True, 'valid':True})


def handle_uploads(request, user):
    if request.method == 'POST':
        values = request.POST.getlist('files[]')
        action = request.POST['action']
        if action == 'delete':
            for i in values:
                DictFile.objects.get(pk=int(i)).delete()
        else:
            for i in values:
                DictFile.objects.get(pk=int(i)).add_es()
    files = DictFile.objects.filter(user=request.user)
    return render(request, 'user_files.html', {'files': files})

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>HSE DICT</title>
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">

      <!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
      <style>
          .w3-container {border-top-left-radius: 0.6em; border-top-right-radius: 0.6em}
          .w3-card-4 {position: relative; width: 320px; margin: 1rem; border-radius: 0.6em}
          .grid-item { width: 320px; margin-bottom: 10px; float: left}
      </style>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index'%}">Вышка Словари</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'index'%}">Поиск</a></li>
            <li><a href="{% url 'about'%}">О проекте</a></li>
              <li><a href="{% url 'help'%}">Помощь</a></li>
          </ul>
            <ul class="nav navbar-nav  navbar-right">
               {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'profile' request.user.username %}">{{ request.user.first_name }} {{ request.user.last_name }}</a>.
                </li>
                <li>
                    <a href="{% url 'logout' %}?next={{ request.path }}">Выйти</a>
                </li>
              {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}">Войти</a></li>
                <li><a href="{% url 'register' %}?next={{ request.path }}">Зарегистрироваться</a></li>
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

       {% block container %}

        {% endblock %}

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
{#    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>#}
  <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
  </body>
</html>

templates/_base_basic.html
{% extends '_base.html' %}

{% block container %}
	{{ block.super }}

	{% block body %}
	{% endblock %}
{% endblock %}

templates/about.html
{% extends '_base_basic.html' %}
{% load static %}
{% block body %}
  <h1>О проекте "Вышка.Словари"</h1>

    <p>
    Вышка.Словари - это веб-ресурс, на котором собрано большое количество как переводных, так и толковых словарей, по которым пользователь может совершать поиск. 
    </p>
    <p>
    Чем проект "Вышка.Словари" отличается от существующих словарных ресурсов?
    </p>
    <ul>
        <li>В наш проект планируется включить данные уникальных словарей, которые еще не выложены в открытый доступ, таких как, например, “Активный словарь русского языка” (под редакцией Ю. Д. Апресяна) и “Словарь бытовой терминологии русского языка” Б. Л. Иомдина.</li>
        <li>Наш лексикографический ресурс активно использует возможности современной компьютерной лингвистики: автоматическое извлечение коллокаций, предоставление данных о частотности слов, об их сочетании и использовании. </li>
        <li>Ресурс существует не только как онлайн-словарь, но и как агрегатор данных: другие пользователи смогут загружать на ресурс свои собственные словари в формате TEI, которые автоматически обрабатываются и добавляются в базу данных Вышка.Словарей.</li>
    </ul>
    <p>Объединение в одном проекте большого количества общедоступных словарей, авторских, недоступных в сети материалов и количественных данных делает Вышка.Словари уникальным лексикографическим ресурсом.</p>

    <p></p>

    <p class="text-danger">Сейчас проект находится в разработке и вы смотрите beta-версию.</p>

    <h3 class="text-center">Загруженные файлы</h3>
		<form method="post" class="form-horizontal" role="form">
			{% csrf_token %}
            <table  class="table">
            <thead>
            <tr><th>Название</th>
                <th>Имя файла</th>
            <td>Дата</td>
            <td>Кто загрузил</td></tr>
            </thead>
            <tbody>
			{% for f in files %}
                <tr>
                <td>{{ f.name }}</td>
                    <td><a href="{{ f.file.url }}"> {{ f.file }}</a></td>
                    <td>{{ f.uploaded_at }}</td>
                    <td>{{ f.user.last_name }} {{ f.user.first_name }}</td>
                </tr>

            {% endfor %}
            </tbody>
            </table>
{% endblock %}

templates/dict_upload.html
{% extends '_base_basic.html' %}
{% load static %}

{% block headers %}
	{{ block.super }}

{% endblock %}

{% block body %}
	<div class="rate-container">
    <div class="col-sm-3">
        <div class="row">
            <h3 class="text-center"></h3>
            <p><a href="{% url "handle_uploads" request.user %}">Просмотреть добавленные файлы.</a></p>

            <p><a href="{% url 'profile'  request.user  %}">На страницу профиля.</a></p>
        </div>
    </div>
    <div class="col-sm-9">
        <div class="row">
           <h3 class="text-center">Добавление нового словаря</h3>

        {#		{% if error %}#}
        {#			<div class="text-danger invalid_login">{{ error }}</div>#}
        {#		{% endif %}#}

            {% if show_form %}

                {% if not valid %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    Файл не прошел валидацию.
                    </div>
                    {% if error %}
                        <div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        Cообщение об ошибке:<br>
                         <code>{{ error }}</code>
                        </div>
                    {% endif %}
                    {% endif %}

                <br><br>

                <form action="{% url 'upload' request.user %}" method="post" enctype="multipart/form-data" class="form-horizontal" role="form">
                    {% csrf_token %}

                    <div class="input-group">
                        <label for="id_file" class="col-sm-4 control-label">Файл со словарем TEI</label>
                        <div class="col-sm-5">
                            <input id="id_file"  type="file" class="form-control" name="file" required>
                        </div>
                      <span class="input-group-btn">
                        <button type="submit" class="btn btn-success">Загрузить</button>
                      </span>
                    </div>
                        <p class="text-danger text-center">Файл должен быть в кодировке UTF-8.</p>
                    <label for="id_user" hidden>User:</label>
                    <input id="id_user" class="form-control hidden" name="user" value="{{ request.user.id }}" required hidden>
                </form>
            {% endif %}

            {% if not show_form %}
                {% if valid %}
                    <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    Файл прошел валидацию.
                    </div>
            {% endif %}
                <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    Файл загружен!
                    </div>
                <p><a href="{% url "upload" request.user %}">Загрузить новый файл.</a></p>
          {% endif %}

        <br><br>
		
		        <h3 class="text-center">Что нужно знать про теги?</h3>
				
		<p>Следующие теги являются плоскими, то есть внутри них не должно быть каких-то других тегов, а может быть только простой текст или число: <code>name</code>, <code>p</code>, <code>extent</code>, <code>author</code>, <code>publisher</code>, <code>editor</code>, <code>edition</code>, <code>translator</code>, <code>pubdate</code>, <code>isbn</code>, <code>iso</code>, <code>text</code>, <code>index</code>, <code>symbol</code>, <code>metalemma</code>, <code>pic</code>, <code>set</code>, <code>quote</code>, <code>hyph</code>, <code>pos</code>, <code>gender</code>, <code>num</code>, <code>per</code>, <code>animat</code>, <code>declen</code>, <code>mood</code>, <code>asp</code>, <code>transit</code>, <code>pron_type</code>, <code>gov</code>, <code>iType</code>, <code>case</code>, <code>tns</code>, <code>paradigm</code>.</p>

		 <br>
		 
        <h3 class="text-center">Как валидируется словарь?</h3>

        <p>Для валидации используется файл XSD (XML Schema Definition), в котором прописано, какие тэги разрешены, как они могут быть вложены, какие атрибуты разрешены и какие у них могут быть значения. Здесь вы можете посмотреть на файл, по которому мы проверяем словари: <code><a target="_blank" href="https://gist.github.com/elmiram/33ec69ae043967fed4bb135c7af89864">scheme.xsd</a></code></p>.

        <p>Вы также можете предварительно на своем компьютере проверить, проходит ли ваш файл валидацию. Для этого нужно:<p>
            <ol>
            <li>Скачать код <code><a target="_blank" href="https://gist.github.com/elmiram/58eba8dc3a1e23753ef2c6fac45086cc">validate.py</a></code> и схему <code><a target="_blank" href="https://gist.github.com/elmiram/33ec69ae043967fed4bb135c7af89864">scheme.xsd</a></code>; </li>
            <li>Прописать в коде путь к схеме и путь к файлу со словарем;</li>
            <li>Запустить и посмотреть результат.</li>
        </ol>

 <br>

        <h3 class="text-center">Где найти шаблон?</h3>
        <p>Описание структуры словаря можно найти в файле <a target="_blank" href="https://docs.google.com/spreadsheets/d/1VOcDUqM16MkZQngB47oh23eYHDomitiPnNkTpDBTDos/edit#gid=907384933">TEI-шаблон</a> на листе "Block Structure". Там описаны все блоки и тэги, которые разрешены внутри этих блоков. Свободные тэги разрешены почти в любом блоке. </p>

            <p>Более строго все описано в схеме <code><a target="_blank" href="https://gist.github.com/elmiram/33ec69ae043967fed4bb135c7af89864">scheme.xsd</a></code>. Например:</p>
        <ul>
            <li><code>xs:element name="..."</code> указывает на тэг</li>
            <li><code>xs:element ref="..."</code> указывает все тэги, которые разрешены внутри соответствующего <code>xs:element name="..."</code></li>
        </ul>
<br><br>
        </div>
    </div>




	</div>
{% endblock %}

templates/help.html
{% extends '_base_basic.html' %}

{% block body %}
  <h1>Помощь</h1>

    <h3>Как загрузить словарь?</h3>

    <ol>
        <li>Чтобы загрузить словарь, нужно <a href="{% url 'register' %}?next={{ request.path }}">зарегистрироваться</a> и <a href="{% url 'login' %}?next={{ request.path }}">войти</a> под своим логином. При регистрации, пожалуйста, укажите ваши настоящие имя и фамилию.</li>
        <li>Зайдите на страницу своего профиля. Ссылка на страницу находится в верхнем меню справа: там отображается ваше имя.</li>
        <li>Теперь вы можете перейти к загрузке словаря или просмотру ваших загруженных файлов.</li>
        <li>После загрузки нужно убедиться, что ваш словарь появился на странице <a href="{% url 'about' %}">О проекте</a>.</li>

    </ol>

    <p>Если файл со словарем очень большой, то его загрузка на сервер может длиться довольно долго - придется подождать.</p>
    <p>Если вы хотите заменить словарь, то старую версию можно удалить в списке ваших загруженных файлов.</p>
{% endblock %}

templates/index.html
{% extends '_base_basic.html' %}

{% block body %}
    <form action="#">
    <div class="form-group">
        <div class="input-group">
          <input type="text" id="search" name="q" value="{{ q }}" class="form-control" placeholder="Введите запрос" required autofocus>
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Искать</button>
          </span>
        </div><!-- /input-group -->
    </div>
    </form>
    {% if total and total != '0' %}
<p>Всего результатов: {{ total }}</p>
    {% endif %}
    <div class="container grid"  data-masonry='{  }'>

      {% for w in words %}
        <div class="w3-card-4 grid-item">
            <header class="w3-container w3-cyan">
              <h4>{{ w.word | safe}} </h4>
            </header>
            <div class="w3-container">
              <p> {{ w.content | safe}} <a style="float: right; margin-bottom: 0.3em; "> &dArr; </a></p>
            </div>

        </div>
      {% endfor %}

    </div>
{% endblock %}

templates/login.html
{% extends '_base_basic.html' %}
{% load static %}

{% block headers %}
	{{ block.super }}

{% endblock %}

{% block body %}
	<div class="rate-container">
    <div class="col-sm-offset-2 col-sm-8">


		<h3 class="text-center">Вход для зарегистрированных пользователей</h3>

		<div class="text-danger invalid_login">{% if form.errors %}Неверное имя пользователя или пароль{% endif %}</div>

		<form method="post" action="{% url 'login' %}" class="login_form" role="form">
			{% csrf_token %}
			<input type="hidden" name="next" value="{{ next }}">

			<div class="form-group">
				<input type="text" name="username" class="form-control" placeholder="Имя пользователя" required autofocus>
				<input type="password" name="password" class="form-control" placeholder="Пароль" required>
			</div>

			<button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
    		<a class="btn btn-sm btn-info btn-block" href="{% url "password_reset_recover" %}">Забыли пароль?</a>
		</form>
    </div>
	</div>
{% endblock %}

templates/profile.html
{% extends '_base_basic.html' %}
{% load static %}

{% block body %}
  <div id='profile'>
  <p><a href="{% url 'upload' request.user %}">Загрузить словарь.</a></p>
<p><a href="{% url "handle_uploads" request.user %}">Просмотреть добавленные файлы.</a></p>
  </div>
{% endblock %}

templates/register.html
{% extends '_base_basic.html' %}
{% load static %}

{% block headers %}
	{{ block.super }}

{% endblock %}

{% block body %}
	<div class="rate-container">

		<h3 class="text-center">Регистрация нового пользователя</h3>

		{% if error %}
			<div class="text-danger invalid_login">{{ error }}</div>
		{% endif %}

		<form action="{% url 'register' %}?next={{ next_page }}" method="post" class="form-horizontal register_form" role="form">
			{% csrf_token %}

			<div class="row form-group">
				<label for="username" class="col-sm-4 control-label">Логин</label>
				<div class="col-sm-5">
					<input type="text" class="form-control" id="username" name="username" placeholder="Логин" required autofocus>
				</div>
			</div>

			<div class="row form-group">
				<label for="first_name" class="col-sm-4 control-label">Имя, фамилия</label>
				<div class="col-sm-5 two_columns">
					<div class="col-sm-6 left_column">
						<input type="text" class="form-control" id="first_name" name="first_name" placeholder="Имя" required>
					</div>
					<div class="col-sm-6 right_column">
						<input type="text" class="form-control" id="last_name" name="last_name" placeholder="Фамилия" required>
					</div>
				</div>
			</div>


			<div class="row form-group">
				<label for="email" class="col-sm-4 control-label">Почта</label>
				<div class="col-sm-5">
					<input type="text" class="form-control" id="email" name="email" placeholder="Почта" required>
				</div>
			</div>
			<div class="row form-group">
				<label for="email" class="col-sm-4 control-label">Пароль</label>
				<div class="col-sm-5 two_columns">
					<div class="col-sm-6 left_column">
						<input type="password" class="form-control" id="password" name="password" placeholder="Пароль" required>
					</div>
					<div class="col-sm-6 right_column">
						<input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Подтверждение пароля" required>
					</div>
				</div>
			</div>

			<div class="row text-center">
				<button type="submit" class="btn btn-success">Зарегистрироваться</button>
			</div>
		</form>
	</div>
{% endblock %}

templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вышка Словари</title>
</head>
<body>

<table>
    <tr>
        <td width="60%" valign="top">
            <h2>Поиск</h2>
            <form action="/slovari/search">
                <input type="text" name="q" placeholder="Введите слово" value="{{ word  }}" autofocus>
                <input type="submit" value="Искать">
            </form>
            {% if empty %}
                <p>Я ничего не нашел. (╯°□°)╯︵ ┻━┻ </p>
            {% else %}
                    <ol>
                    {% for key, values in trans.items %}
                        <h3>{{ key }}</h3>
                        {% for i in values %}
                        <li>{{ i.token1.text }} - {{ i.token2.text }} [{{ i.token2.lang }}] ({{ i.source }})</li>
                        {% endfor %}
                    {% endfor %}
                    </ol>
        {% endif %}

        </td>
        <td valign="top">
            <h2>Последние запросы:</h2>
            {% for i in queries %}
                <p>{{ i }}</p>
            {% endfor %}
        <a href="/">На главную</a>
        </td>
    </tr>
</table>

</body>
</html>

templates/user_files.html
{% extends '_base_basic.html' %}
{% load static %}

{% block headers %}
	{{ block.super }}

{% endblock %}

{% block body %}
	<div class="rate-container">

    {% if files %}
       <h3 class="text-center">Вы зарузили эти файлы:</h3>
		<form method="post" class="form-horizontal" role="form">
			{% csrf_token %}
            <table  class="table">
            <thead>
            <tr><th>Имя файла</th>
            <td>Дата</td></tr>
            </thead>
            <tbody>
			{% for f in files %}
                <tr>
                    <td><input type="checkbox" value="{{ f.id }}" id="dictfile{{ f.id }}" name="files[]"> <label for="dictfile{{ f.id }}">{{ f.file }}</label></td>
                    <td>{{ f.uploaded_at }}</td>
                </tr>

            {% endfor %}
            </tbody>
            </table>
            <label> Что сделать с выбранными файлами?
                <select name="action" class="form-control">
                    <option value="delete">удалить</option>
{#                    <option value="">добавить в индекс</option>#}
                </select>
            </label>
            <div class="row text-center">
				<button type="submit" class="btn btn-success">Выполнить</button>
			</div>
		</form>
    {% endif %}
    {% if  not files %}
    <p>У вас нет загруженных файлов</p>
  {% endif %}

 <p><a href="{% url 'profile'  request.user  %}">На страницу профиля.</a></p>
	</div>
{% endblock %}